### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by GregKuhlmann** [llSourcell/autoencoder_demo#1]
Upon running `python main.py` I get the following error:
```
('Extracting', 'MNIST_data/train-images-idx3-ubyte.gz')
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
  File "/Users/kuhlmann/autoencoder_demo/input_data.py", line 150, in read_data_sets
    train_images = extract_images(local_file)
  File "/Users/kuhlmann/autoencoder_demo/input_data.py", line 40, in extract_images
    buf = bytestream.read(rows * cols * num_images)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 275, in read
    chunk = self.extrabuf[offset: offset + size]
TypeError: only integer scalar arrays can be converted to a scalar index
```

Fixed by following advice here:
http://stackoverflow.com/questions/42128830/typeerror-only-integer-scalar-arrays-can-be-converted-to-a-scalar-index

**Comment by anasvp444** [comment]
add [0] to the function _read32 in input_data.py

def _read32(bytestream):
    dt = numpy.dtype(numpy.uint32).newbyteorder('>')
    return numpy.frombuffer(bytestream.read(4), dtype=dt)[0]

**Comment by psnehanshu** [comment]
![98cdf4cce79267bfc10dc965adac57ae](https://user-images.githubusercontent.com/9392350/33238769-ee6f5a90-d2b9-11e7-9f32-a3a4a5251815.jpg)
